/** mongocamp No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.7.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package com.quadstingray.mongo.camp.client.api

import com.quadstingray.mongo.camp.client.core.JsonSupport._
import com.quadstingray.mongo.camp.client.model._
import com.quadstingray.mongo.camp.converter.CirceSchema
import sttp.client3._
import sttp.client3.circe.asJson
import sttp.model.Method

object AdminApi {

  def apply(baseUrl: String = com.quadstingray.mongo.camp.server.TestServer.serverBaseUrl) = new AdminApi(baseUrl)
}

class AdminApi(baseUrl: String) extends CirceSchema {

  /** Add a new Role
    *
    * Expected answers: code 200 : Role code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param role
    */
  def addRole(apiKey: String, bearerToken: String)(role: Role) =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/admin/roles")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(role)
      .response(asJson[Role])

  /** Add a new User
    *
    * Expected answers: code 200 : UserProfile code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userInformation
    */
  def addUser(apiKey: String, bearerToken: String)(userInformation: UserInformation) =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/admin/users")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(userInformation)
      .response(asJson[UserProfile])

  /** Delete Role
    *
    * Expected answers: code 200 : JsonResultBoolean code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the
    * MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param roleName
    *   RoleKey
    */
  def deleteRole(apiKey: String, bearerToken: String)(roleName: String) =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/admin/roles/$roleName")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[JsonResultBoolean])

  /** Delete User
    *
    * Expected answers: code 200 : JsonResultBoolean code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the
    * MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userId
    *   UserId to Delete
    */
  def deleteUser(apiKey: String, bearerToken: String)(userId: String) =
    basicRequest
      .method(Method.DELETE, uri"$baseUrl/admin/users/$userId")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[JsonResultBoolean])

  /** Get Role by RoleKey
    *
    * Expected answers: code 200 : Role code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param roleName
    *   RoleKey to search
    */
  def getRole(apiKey: String, bearerToken: String)(roleName: String) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/admin/roles/$roleName")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[Role])

  /** Get UserProfile for user
    *
    * Expected answers: code 200 : UserProfile code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userId
    *   UserId to search
    */
  def getUser(apiKey: String, bearerToken: String)(userId: String) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/admin/users/$userId")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[UserProfile])

  /** Generate an new APIkey for the user
    *
    * Expected answers: code 200 : JsonResultString code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the
    * MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userId
    *   UserId to Update
    */
  def gnerateNewApiKeyForUser(apiKey: String, bearerToken: String)(userId: String) =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/admin/users/$userId/apikey")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[JsonResultString])

  /** List all Roles or filtered
    *
    * Expected answers: code 200 : Seq[Role] Headers : x-pagination-count-rows - count all elements x-pagination-rows-per-page - Count elements per page
    * x-pagination-current-page - Current page x-pagination-count-pages - Count pages code 400 : String (Invalid value for: query parameter filter, Invalid
    * value for: query parameter rowsPerPage, Invalid value for: query parameter page) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param filter
    *   filter after userId by contains
    * @param rowsPerPage
    *   Count elements per page
    * @param page
    *   Requested page of the ResultSets
    */
  def listRoles(
      apiKey: String,
      bearerToken: String
  )(filter: Option[String] = None, rowsPerPage: Option[Long] = None, page: Option[Long] = None) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/admin/roles?filter=$filter&rowsPerPage=$rowsPerPage&page=$page")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[Seq[Role]])

  /** List all Users or filtered
    *
    * Expected answers: code 200 : Seq[UserProfile] Headers : x-pagination-count-rows - count all elements x-pagination-rows-per-page - Count elements per page
    * x-pagination-current-page - Current page x-pagination-count-pages - Count pages code 400 : String (Invalid value for: query parameter filter, Invalid
    * value for: query parameter rowsPerPage, Invalid value for: query parameter page) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param filter
    *   filter after userId by contains
    * @param rowsPerPage
    *   Count elements per page
    * @param page
    *   Requested page of the ResultSets
    */
  def listUsers(apiKey: String, bearerToken: String)(
      filter: Option[String] = None,
      rowsPerPage: Option[Long] = None,
      page: Option[Long] = None
  ) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/admin/users?filter=$filter&rowsPerPage=$rowsPerPage&page=$page")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[Seq[UserProfile]])

  /** Change Password of User
    *
    * Expected answers: code 200 : JsonResultBoolean code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userId
    *   UserId to Update
    * @param passwordUpdateRequest
    */
  def updatePasswordForUser(
      apiKey: String,
      bearerToken: String
  )(userId: String, passwordUpdateRequest: PasswordUpdateRequest) =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/admin/users/$userId/password")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(passwordUpdateRequest)
      .response(asJson[JsonResultBoolean])

  /** Update Role
    *
    * Expected answers: code 200 : Role code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param roleName
    *   RoleKey
    * @param updateRoleRequest
    */
  def updateRole(
      apiKey: String,
      bearerToken: String
  )(roleName: String, updateRoleRequest: UpdateRoleRequest) =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/admin/roles/$roleName")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(updateRoleRequest)
      .response(asJson[Role])

  /** Update Roles of User
    *
    * Expected answers: code 200 : UserProfile code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param userId
    *   UserId to Update
    * @param requestBody
    */
  def updateRolesForUser(
      apiKey: String,
      bearerToken: String
  )(userId: String, requestBody: Seq[String]) =
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/admin/users/$userId/roles")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(requestBody)
      .response(asJson[UserProfile])

}
