/** mongocamp No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.3.1
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package com.quadstingray.mongo.camp.client.api

import com.quadstingray.mongo.camp.client.core.JsonSupport._
import com.quadstingray.mongo.camp.client.model.InsertResponse
import com.quadstingray.mongo.camp.converter.CirceSchema
import sttp.client3._
import sttp.model.Method

object CreateApi {

  def apply(baseUrl: String = com.quadstingray.mongo.camp.server.TestServer.serverBaseUrl) = new CreateApi(baseUrl)
}

class CreateApi(baseUrl: String) extends CirceSchema {

  /** Insert one Document in Collection
    *
    * Expected answers: code 200 : InsertResponse code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param collectionName
    *   The name of your MongoDb Collection
    * @param requestBody
    *   JSON Representation for your Document.
    */
  def insert(
      apiKey: String,
      bearerToken: String
  )(collectionName: String, requestBody: Map[String, Any]) =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/mongodb/collections/$collectionName/insert")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(requestBody)
      .response(asJson[InsertResponse])

  /** Insert many documents in Collection
    *
    * Expected answers: code 200 : InsertResponse code 400 : String (Invalid value for: body) code 0 : ErrorDescription Headers : x-error-code - Error Code
    * x-error-message - Message of the MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    *
    * @param collectionName
    *   The name of your MongoDb Collection
    * @param requestBody
    */
  def insertMany(
      apiKey: String,
      bearerToken: String
  )(collectionName: String, requestBody: Seq[Map[String, Any]]) =
    basicRequest
      .method(Method.PUT, uri"$baseUrl/mongodb/collections/$collectionName/insert/many")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .body(requestBody)
      .response(asJson[InsertResponse])

}
