/** mongocamp-server No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.11.1-SNAPSHOT
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.mongocamp.server.client.model

case class Field(
    name: String,
    fieldTypes: Option[Seq[FieldType]] = None,
    count: Long,
    percentageOfParent: Double,
    subFields: Option[Seq[Field]] = None
)
