/** mongocamp-server No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.13.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.mongocamp.server.client.api

import dev.mongocamp.server.client.core.JsonSupport._
import dev.mongocamp.server.client.model.{JsonValueAny, JsonValueBoolean, Metric, MongoCampConfiguration}
import dev.mongocamp.server.converter.CirceSchema
import dev.mongocamp.server.model.SettingsResponse
import dev.mongocamp.server.server.TestServer
import sttp.client3._
import sttp.client3.circe.asJson
import sttp.model.Method

object ApplicationApi {
  def apply(baseUrl: String = TestServer.serverBaseUrl) = new ApplicationApi(baseUrl)
}

class ApplicationApi(baseUrl: String) extends CirceSchema {

  /** Returns the Metrics of events of the running MongoCamp Application.
    *
    * Expected answers: code 200 : Seq[Metric] code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    */
  def eventMetrics(apiKey: String, bearerToken: String)() = basicRequest
    .method(Method.GET, uri"$baseUrl/system/monitoring/events")
    .contentType("application/json")
    .header("X-AUTH-APIKEY", apiKey)
    .auth
    .bearer(bearerToken)
    .response(asJson[Seq[Metric]])

  /** Returns the JVM Metrics of the running MongoCamp Application
    *
    * Expected answers: code 200 : Seq[Metric] code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    */
  def jvmMetrics(apiKey: String, bearerToken: String)() = basicRequest
    .method(Method.GET, uri"$baseUrl/system/monitoring/jvm")
    .contentType("application/json")
    .header("X-AUTH-APIKEY", apiKey)
    .auth
    .bearer(bearerToken)
    .response(asJson[Seq[Metric]])

  /** Returns the MongoDB Metrics of the running MongoCamp Application
    *
    * Expected answers: code 200 : Seq[Metric] code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    */
  def mongoDbMetrics(apiKey: String, bearerToken: String)() = basicRequest
    .method(Method.GET, uri"$baseUrl/system/monitoring/mongodb")
    .contentType("application/json")
    .header("X-AUTH-APIKEY", apiKey)
    .auth
    .bearer(bearerToken)
    .response(asJson[Seq[Metric]])

  /** Returns the Metrics of the MongoCamp System
    *
    * Expected answers: code 200 : Seq[Metric] code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the MongoCampException
    * x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    */
  def systemMetrics(apiKey: String, bearerToken: String)() = basicRequest
    .method(Method.GET, uri"$baseUrl/system/monitoring/system")
    .contentType("application/json")
    .header("X-AUTH-APIKEY", apiKey)
    .auth
    .bearer(bearerToken)
    .response(asJson[Seq[Metric]])

  /** Returns the Settings of the running MongoCamp Application.
    *
    * Expected answers: code 200 : SettingsResponse code 0 : ErrorDescription Headers : x-error-code - Error Code x-error-message - Message of the
    * MongoCampException x-error-additional-info - Additional information for the MongoCampException
    *
    * Available security schemes: apiKeyAuth (apiKey) httpAuth (http)
    */
  def settings(apiKey: String, bearerToken: String)() =
    basicRequest
      .method(Method.GET, uri"$baseUrl/system/settings")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth
      .bearer(bearerToken)
      .response(asJson[SettingsResponse])

  /**
   * Update Configuration with the value
   *
   * Expected answers:
   * code 200 : JsonValueBoolean
   * code 400 : String (Invalid value for: body)
   * code 0 : ErrorDescription
   * Headers :
   * x-error-code - Error Code
   * x-error-message - Message of the MongoCampException
   * x-error-additional-info - Additional information for the MongoCampException
   *
   * Available security schemes:
   * apiKeyAuth (apiKey)
   * httpAuth (http)
   * httpAuth1 (http)
   *
   * @param configurationKey configurationKey to edit
   * @param jsonValueAny
   */
  def updateConfiguration(apiKey: String, bearerToken: String)(configurationKey: String, jsonValueAny: JsonValueAny)=
    basicRequest
      .method(Method.PATCH, uri"$baseUrl/system/configurations/${configurationKey}")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth.bearer(bearerToken)
      .body(jsonValueAny)
      .response(asJson[JsonValueBoolean])

  /**
   * List all Configurations or filtered
   *
   * Expected answers:
   * code 200 : Seq[MongoCampConfiguration]
   * code 0 : ErrorDescription
   * Headers :
   * x-error-code - Error Code
   * x-error-message - Message of the MongoCampException
   * x-error-additional-info - Additional information for the MongoCampException
   *
   * Available security schemes:
   * apiKeyAuth (apiKey)
   * httpAuth (http)
   * httpAuth1 (http)
   */
  def listConfigurations(apiKey: String, bearerToken: String)()=
    basicRequest
      .method(Method.GET, uri"$baseUrl/system/configurations")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth.bearer(bearerToken)
      .response(asJson[Seq[MongoCampConfiguration]])


  /**
   * Get Configuration for key
   *
   * Expected answers:
   * code 200 : MongoCampConfiguration
   * code 0 : ErrorDescription
   * Headers :
   * x-error-code - Error Code
   * x-error-message - Message of the MongoCampException
   * x-error-additional-info - Additional information for the MongoCampException
   *
   * Available security schemes:
   * apiKeyAuth (apiKey)
   * httpAuth (http)
   * httpAuth1 (http)
   *
   * @param configurationKey configurationKey to get
   */
  def getConfig(apiKey: String, bearerToken: String)(configurationKey: String) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/system/configurations/${configurationKey}")
      .contentType("application/json")
      .header("X-AUTH-APIKEY", apiKey)
      .auth.bearer(bearerToken)
      .response(asJson[MongoCampConfiguration])
}
