/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.mongocamp.server.test.client.api

import dev.mongocamp.server.test.TestServer
import dev.mongocamp.server.test.client.core.JsonSupport._
import dev.mongocamp.server.test.client.model.Version
import sttp.client3._
import sttp.model.Method

object SystemApi {
  def apply(baseUrl: String = TestServer.serverBaseUrl) = new SystemApi(baseUrl)
}

class SystemApi(baseUrl: String) {

  /**
   * Returns the List of all registered Jobs with full information
   * 
   * Expected answers:
   *   code 200 : ClusterInformation ()
   *   code 0 : ErrorDescription ()
   *              Headers :
   *                x-error-code - Error Code
   *                x-error-message - Message of the MongoCampException
   *                x-error-additional-info - Additional information for the MongoCampException
   * 
   * Available security schemes:
   *   httpAuth1 (http)
   *   httpAuth (http)
   *   apiKeyAuth (apiKey)
   */
  def viewCluster(username: String, password: String, bearerToken: String, apiKey: String)(
)=
    basicRequest
      .method(Method.GET, uri"$baseUrl/system/cluster")
      .contentType("application/json")
      .auth.basic(username, password)
      .auth.bearer(bearerToken)
      .header("X-AUTH-APIKEY", apiKey)
      .response(asEither(asString, ignore))

  /** Version Info of the MongoCamp API
   *
   * Expected answers: code 200 : Version () code 0 : ErrorDescription () Headers : x-error-code - Error Code x-error-message - Message of the
   * MongoCampException x-error-additional-info - Additional information for the MongoCampException
   */
  def version(
             ) =
    basicRequest
      .method(Method.GET, uri"$baseUrl/version")
      .contentType("application/json")
      .response(asJson[Version])

}
