/** mongocamp No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 0.5.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package com.quadstingray.mongo.camp.client.model

case class IndexOptionsRequest(
    name: Option[String] = None,
    background: Option[Boolean] = None,
    defaultLanguage: Option[String] = None,
    textVersion: Option[Int] = None,
    expireAfter: Option[String] = None,
    unique: Option[Boolean] = None,
    max: Option[Double] = None,
    min: Option[Double] = None
)
