/**
 * mongocamp-library
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.5.11
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package dev.mongocamp.server.test.client.model

case class ClusterMemberInformation(
  name: String,
  siteMaster: Boolean,
  siteAddress: Boolean,
  multicast: Boolean,
  coordinator: Boolean
)

