/** mongocamp-server No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
  *
  * The version of the OpenAPI document: 1.4.0
  *
  * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). https://openapi-generator.tech Do not edit the class manually.
  */
package dev.mongocamp.server.test.client.model

import org.joda.time.DateTime

case class JobInformation(
    name: String,
    group: String,
    jobClassName: String,
    description: Option[String],
    cronExpression: String,
    priority: Int,
    lastScheduledFireTime: Option[DateTime] = None,
    nextScheduledFireTime: Option[DateTime] = None,
    scheduleInformation: Option[String] = None
)
