name: Run Tests

on:
  pull_request:
    branches-ignore:
      - 'main'
  push:
    branches-ignore:
      - 'main'

jobs:
  #  code_quality:
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: 'Qodana Scan'
  #        uses: JetBrains/qodana-action@main
  #        env:
  #           QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        mongodb-version: [ '4.4', '5.0', '6.0' ]
        os: [ ubuntu-latest ]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0
      - name: Setup TimeZone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Europe/Berlin"
          timezoneMacos: "Europe/Berlin"
          timezoneWindows: "W. Europe Standard Time"
      - name: Set up JDK
        uses: coursier/setup-action@v1
        with:
          jvm: graalvm-java17:22.3.2
          apps: sbt scala scalac
      - name: Start MongoDB ${{ matrix.mongodb-version }}
        uses: MongoCamp/mongodb-github-action@1.2.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-port: 4711
      - name: Run tests
        run: sbt test
      - name: Build Docker Container for test
        run: docker buildx build --platform=linux/amd64,linux/arm64/v8 . --tag mongocamp-server:test