name: Run Build and Release Process

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0
      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Run tests
        run: sbt test
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build Docker Container for GitHub Registry
        env:
          DOCKER_GIT_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_GIT_PASSWORD: ${{ secrets.GH_ADMIN_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          docker login docker.pkg.github.com -u DOCKER_GIT_USERNAME -p DOCKER_GIT_PASSWORD
          docker login ghcr.io -u DOCKER_GIT_USERNAME -p DOCKER_GIT_PASSWORD
          docker login -u DOCKER_HUB_USERNAME -p DOCKER_HUB_PASSWORD
          sbt ci-docker
  build-docu:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.0.2
      - name: Build Docu and deploy to GitHub
        env:
          GITHUB_USER: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          git config --global user.email "ci@mongocamp.dev"
          git config --global user.name "MongoCamp CI"
          sbt ci-deploy-docu
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.0.2
      - name: install conventional-changelog-cli
        run: pnpm install -g conventional-changelog-cli
      - name: install conventional-github-release
        run: pnpm install -g conventional-github-releaser
      - name: Set up JDK
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
          GITHUB_USER: ${{ secrets.DOCKER_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}
        run: |
          git config --global user.email "ci@mongocamp.dev"
          git config --global user.name "MongoCamp CI"
          sbt ci-release
