name: Run Tests

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        jdk: [openjdk@1.17.0]
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK ${{ matrix.jdk }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run tests
        run: sbt test
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.17.0
      - name: Build Docker Container for GitHub Registry
        run: |
          if grep -q "SNAPSHOT" version.sbt
          then
              echo 'Nothing to do';
          else
            docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            sbt docker:publish
          fi
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.17.0
      - name: Release
        run: |
          if grep -q "SNAPSHOT" version.sbt
          then
              echo 'Nothing to do';
          else
            git config --global user.email "ci@quadstingray.com"
            git config --global user.name "QuadStingray CI"
            sbt "release with-defaults"
          fi
