name: Run Build and Release Process

on:
  push:
    branches: [ main ]
  repository_dispatch:
    types: [build]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        jdk: [openjdk@1.17.0]
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT ivy cache
        uses: actions/cache@v2
        with:
          path: ~/.ivy2/cache
          key: ${{ runner.os }}-sbt-ivy-cache-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Set up JDK ${{ matrix.jdk }}
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.jdk }}
      - name: Run tests
        run: sbt test
  build-docker:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.17.0
      - name: Build Docker Container for GitHub Registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker login ghcr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          sbt ci-docker
  build-docu:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.0.2
      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'  
      - name: Build Docu and deploy to GitHub
        run: sbt ci-deploy-docu
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.0.2
      - name: install conventional-changelog-cli
        run: pnpm install -g conventional-changelog-cli
      - name: install conventional-github-release
        run: pnpm install -g conventional-github-releaser
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.17.0
      - name: Release
        env:
          CONVENTIONAL_GITHUB_RELEASER_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}
        run: sbt ci-release
